server:
  port: 9527

spring:
  application:
    name: microservice-zuul-gateway
   
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true  
      
zuul:
  prefix: /wpx/
  ignored-services: "*"   # 使用"*"注解表示所有程序原始访问服务路径忽略      microservicecloud-dept
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  SecondFilter:  #禁用过滤器
    pre:
      disable: true


info: 
  app.name: microservicecloud
  company.name: www.wpxcloud.xyz
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  security:
    enabled: false